// PHOTOS
export const RECEIVE_PHOTOS = "RECEIVE_PHOTOS";
export const REQUEST_PHOTOS = "REQUEST_PHOTOS";
export const REQUEST_SEARCH_PHOTOS = "REQUEST_SEARCH_PHOTOS";
export const RECEIVE_SEARCH_PHOTOS = "RECEIVE_SEARCH_PHOTOS";
// COLLECTIONS
export const RECEIVE_COLLECTIONS = "RECEIVE_COLLECTIONS";
export const REQUEST_COLLECTIONS = "REQUEST_COLLECTIONS";

export const REQUEST_SEARCH_COLLECTIONS = "REQUEST_SEARCH_COLLECTIONS";
export const RECEIVE_SEARCH_COLLECTIONS = "RECEIVE_SEARCH_COLLECTIONS";

export const REQUEST_COLLECTION_PHOTOS = "REQUEST_COLLECTION_PHOTOS";
export const RECEIVE_COLLECTION_PHOTOS = "RECEIVE_COLLECTION_PHOTOS";

export const REQUEST_RELATED_COLLECTIONS = "REQUEST_RELATED_COLLECTIONS";
export const RECEIVE_RELATED_COLLECTIONS = "RECEIVE_RELATED_COLLECTIONS";
// DOWNLOAD IMAGE
export const REQUEST_DOWNLOAD_PHOTO = "REQUEST_DOWNLOAD_PHOTO";
export const RECEIVE_DOWNLOAD_PHOTO = "RECEIVE_DOWNLOAD_PHOTO";
// GENERAL TYPES
export const REQUEST_PAGINATION = "REQUEST_PAGINATION";
export const REQUEST_PAGINATION_TYPE = "REQUEST_PAGINATION_TYPE";
export const REQUEST_COLLECTION_ID = "REQUEST_COLLECTION_ID";
